# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_servo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_servo(object):
    def setupUi(self, servo):
        servo.setObjectName("servo")
        servo.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(servo)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.logPlainTextEdit = PlainTextEdit(servo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.logPlainTextEdit.setSizePolicy(sizePolicy)
        self.logPlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 150))
        self.logPlainTextEdit.setObjectName("logPlainTextEdit")
        self.gridLayout_2.addWidget(self.logPlainTextEdit, 2, 0, 1, 1)
        self.ctlCard = CardWidget(servo)
        self.ctlCard.setObjectName("ctlCard")
        self.gridLayout = QtWidgets.QGridLayout(self.ctlCard)
        self.gridLayout.setObjectName("gridLayout")
        self.upButton = ToolButton(self.ctlCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 0, 1, 1, 1)
        self.rightButton = ToolButton(self.ctlCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightButton.sizePolicy().hasHeightForWidth())
        self.rightButton.setSizePolicy(sizePolicy)
        self.rightButton.setObjectName("rightButton")
        self.gridLayout.addWidget(self.rightButton, 1, 2, 1, 1)
        self.leftButton = ToolButton(self.ctlCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton.sizePolicy().hasHeightForWidth())
        self.leftButton.setSizePolicy(sizePolicy)
        self.leftButton.setObjectName("leftButton")
        self.gridLayout.addWidget(self.leftButton, 1, 0, 1, 1)
        self.downButton = ToolButton(self.ctlCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downButton.sizePolicy().hasHeightForWidth())
        self.downButton.setSizePolicy(sizePolicy)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.ctlCard, 0, 0, 2, 1)
        self.setCard = HeaderCardWidget(servo)
        self.setCard.setMinimumSize(QtCore.QSize(150, 0))
        self.setCard.setMaximumSize(QtCore.QSize(250, 16777215))
        self.setCard.setObjectName("setCard")
        self.gridLayout_2.addWidget(self.setCard, 0, 1, 3, 1)

        self.retranslateUi(servo)
        QtCore.QMetaObject.connectSlotsByName(servo)

    def retranslateUi(self, servo):
        _translate = QtCore.QCoreApplication.translate
        servo.setWindowTitle(_translate("servo", "servo"))
from qfluentwidgets import CardWidget, HeaderCardWidget, PlainTextEdit, ToolButton
